// Install VS Code extention "REST Client" to test endpoints in this file

GET http://localhost:5000/products

###

GET http://localhost:5000/products/2

###

POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Test name",
    "description": "Test description",
    "price": 100
}

###

PUT http://localhost:5000/products/6
Content-Type: application/json

{
    "name": "New test name"
}

###

DELETE http://localhost:5000/products/6